name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  release:
    name: ğŸ“¦ Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: ğŸ“š Checkout
        uses: actions/checkout@v4
      - name: ğŸŸ¢ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "^20"
          registry-url: "https://registry.npmjs.org"
      - name: ğŸš€ Setup pnpm
        uses: pnpm/action-setup@v2.4.0
      - name: â†˜ï¸ Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: ğŸ—ï¸ Build Package
        run: pnpm build:npm
      - name: ğŸ“¦ Publish to npm
        working-directory: ./dist
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
